'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with  and , the first  terms will be:
1,2,3,5,8,13,21,34,55,89,.....
By considering the terms in the Fibonacci sequence whose values do not exceed , find the sum of the even-valued terms.
'''


series = [1,2]
n = 10
m = len(series)
for i in range(m,n):
    if (series[i - 1] + series[i - 2] > 10):
        break
    series.append(series[i-1]+series[i-2])

print(series)